### ISSUE TITLE
我成功的运行了您的项目，但是在选好了图片，进行运行时,出现了报错。

### ISSUE THREAD

**Issue by TheYMing** [Ryammmmm/Fast-style-transfer-with-GUI#2]
报错是关于路劲的：
Traceback (most recent call last):
  File "D:\python3.6\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "E:/sf_shiyan_all/Fast-style-transfer-with-GUI/gui.py", line 95, in transfer_img
    final = Image.open(final_path)
  File "E:\carton\venv\lib\site-packages\PIL\Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'images/outputs/starry_night.pth-style03.jpg'

**Comment by TheYMing** [comment]
大概是如下代码并没有运行，导致没有结果图片生成，也就出现了路径报错：
代码如下： os.system("python stylized-image.py {} {}".format(select_img,models_path))
没有运行结果出现！

**Comment by Ryammmmm** [comment]
你好，这个应该是路径问题，项目时间有点久了，有点忘了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ryammmmm/Fast-style-transfer-with-GUI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 中午1:47
收件人:&nbsp;"Ryammmmm/Fast-style-transfer-with-GUI"<Fast-style-transfer-with-GUI@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Ryammmmm/Fast-style-transfer-with-GUI] 我成功的运行了您的项目，但是在选好了图片，进行运行时,出现了报错。 (#2)





 
大概是如下代码并没有运行，导致没有结果图片生成，也就出现了路径报错：
 代码如下： os.system("python stylized-image.py {} {}".format(select_img,models_path))
 没有运行结果出现！

**Comment by Ryammmmm** [comment]
select_img:指你需要进行迁移的图片的绝对路径
models_path:指你需要使用的风格模型的绝对路径
应该都是绝对路径吧，没有记错的话。
你可以在cmd窗口类似于运行gui.py的方式运行stylized-image.py，不过需要进行传参，也就是上面提到的两个参数的绝对路径。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ryammmmm/Fast-style-transfer-with-GUI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 中午1:47
收件人:&nbsp;"Ryammmmm/Fast-style-transfer-with-GUI"<Fast-style-transfer-with-GUI@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Ryammmmm/Fast-style-transfer-with-GUI] 我成功的运行了您的项目，但是在选好了图片，进行运行时,出现了报错。 (#2)





 
大概是如下代码并没有运行，导致没有结果图片生成，也就出现了路径报错：
 代码如下： os.system("python stylized-image.py {} {}".format(select_img,models_path))
 没有运行结果出现！
